### ISSUE TITLE
devspace deploy failes on Windows

### ISSUE THREAD

**Issue by jenisov** [devspace-cloud/devspace#914] opened 2020-02-10 13:08 UTC
**What happened?**  
quickstart-nodejs failes to deploy from windows:

`devspace deploy` reports `Unable to deploy helm chart` either because `not a valid chart repository` or `failed to download`

Note: local devspace installation (Ubuntu 18.04) works well.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
C:\tmp\quickstart-nodejs>devspace deploy
[info]   Using kube context 'microk8s'
[info]   Using namespace 'ttt'
[info]   Skip building image 'default'
[fatal]  Error deploying quickstart-nodejs: Unable to deploy helm chart: looks like
"https://charts.devspace.cloud" is not a valid chart repository or cannot be reached: Get
https://charts.devspace.cloud/index.yaml: dial tcp 167.99.137.12:443: connectex: No connection
could be made because the target machine actively refused it.
Run devspace purge -d quickstart-nodejs and devspace deploy to recreate the chart
C:\tmp\quickstart-nodejs>helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
C:\tmp\quickstart-nodejs>devspace deploy
[info]   Using kube context 'microk8s'
[info]   Using namespace 'ttt'
[info]   Skip building image 'default'
[fatal]  Error deploying quickstart-nodejs: Unable to deploy helm chart: failed to download
"https://charts.devspace.cloud/component-chart-v0.0.8.tgz" (hint: running `helm repo update` may help)     Run devspace purge -d quickstart-nodejs and devspace deploy to recreate the chart
```

**Local Environment:**  
- Operating System: windows
```
PS C:\tmp\quickstart-nodejs> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
PS C:\tmp\quickstart-nodejs> helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
PS C:\tmp\quickstart-nodejs> devspace --version
devspace version 4.5.0
```

**Kubernetes Cluster:**  
- Cloud Provider: microk8s
- Kubernetes Version: 2.17.2

/kind bug

**Comment by LukasGentele** [comment] 2020-02-10 13:21
@jenisov Thanks for reporting this. It looks like your machine cannot download `https://charts.devspace.cloud/component-chart-v0.0.8.tgz`. Can you retry and if it still fails, can you see if it is possible to download the file via browser or wget?

**Comment by jenisov** [comment] 2020-02-10 13:34
This is what I checked first, browser and wget can download https://charts.devspace.cloud/component-chart-v0.0.8.tgz

**Comment by LukasGentele** [comment] 2020-02-10 13:40
@jenisov Thanks! Can you also try to run `helm repo update` ? Another option would be to delete `$HOME/.helm/repository/cache` and `$HOME/.helm/cache`. Does that change anything?

**Comment by jenisov** [comment] 2020-02-10 13:49
I tried before `heml repo update`, it doesn't help. Clearing caches also changes nothing. `deploy` reports fatal either because ` Unable to deploy helm chart: looks like "https://charts.devspace.cloud" is not a valid chart repository` or because `Unable to deploy helm chart: failed to download "https://charts.devspace.cloud/component-chart-v0.0.8.tgz"` (I cannot catch the reason).

**Comment by LukasGentele** [comment] 2020-02-10 13:54
Are you using `componentChart: true` in your devspace.yaml? If yes, you could try to replace it with:
```
  chart:
    name: component-chart
    version: v0.1.1
    repo: https://charts.devspace.sh
```
charts.devspace.sh is the new helm repository. We will switch to this one soon.

**Comment by jenisov** [comment] 2020-02-10 14:05
I'm not sure I put it in a right place, but setting chart's repo still gets fatal for "https://charts.devspace.cloud": `No connection could be made because the target machine actively refused it`

```
deployments:
- name: quickstart-nodejs
  helm:
    componentChart: true
    chart:
      name: component-chart
      version: v0.1.1
      repo: https://charts.devspace.sh
    values:
      containers:
      - image: rtsoft/quickstartnodejs
      service:
        ports:
        - port: 3000
```


One thing: charts.devspace.cloud resoves to 157.230.120.63 and ping is ok, but `devspace` reports:

```
[fatal]  Error deploying quickstart-nodejs: Unable to deploy helm chart: looks like 
"https://charts.devspace.cloud" is not a valid chart repository or cannot be reached: Get 
https://charts.devspace.cloud/index.yaml: dial tcp 167.99.137.12:443: connectex: No connection could 
be made because the target machine actively refused it.
```

couldn't it be DigitalOcean problem?

**Comment by LukasGentele** [comment] 2020-02-10 14:22
You need to remove `componentChart: true`, otherwise the `chart` section will not have any effect.

**Comment by jenisov** [comment] 2020-02-10 14:25
Found a workaround:

Just download `component-chart` locally (`wget https://charts.devspace.sh/charts/component-chart-v0.1.1.tgz`), extract it and replace `componentChart: true` with 
```
    chart:
      name: component-chart
```

Look like `devspace` doesn't resolve `charts.devspace.cloud` and `charts.devspace.sh` correctly

**Comment by LukasGentele** [comment] 2020-02-14 19:47
We are not able reproduce this issue so far. I'm working on Windows 10 myself using DevSpace and cannot reproduce this. To me it seems like a network issue which cannot be addressed by DevSpace.  Does it still exist with today's release? 

If the issue still exists, the following things would be worth testing:
- Are you able to reproduce this on another machine (e.g. one of your colleagues or friends) in the same network?
- Are you able to reproduce this with the same machine in a different network (e.g. home vs public vs office)?

**Comment by jenisov** [comment] 2020-02-16 20:22
I've updated to 4.5.2 and now I cannot reproduce the issue.

**Comment by LukasGentele** [comment] 2020-02-17 18:44
Thanks for checking this again. Great that the issue seems resolved. Closing this for now. Feel free to reopen this issue if the problem occurs again.

**Closed by LukasGentele** 2020-02-17 18:44 UTC
Labels: needs-information

**Comment by jenisov** [comment] 2020-02-18 14:47
Unfortunately last hour the problem is risen again. Updating devspace to 4.5.3 did not help.
Will check on other network later.

**Comment by LukasGentele** [comment] 2020-02-18 15:23
Yes. If it happens irregularly, it is even more reason to believe that this is a network issue. FYI: the chart registry is currently hosted on GCP.
