### ISSUE TITLE
Devspace CLI doesn't work on Windows when installed via npm

### ISSUE THREAD

**Issue by afmsavage** [devspace-cloud/devspace#911] opened 2020-02-09 06:40 UTC
**What happened?**  
Installed devspace via `npm i -g devspace` but when I try to run it in my Powershell prompt, I get this error

```->  ~ devspace
& : The term 'sh.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\afmsa\scoop\apps\nvm\current\nodejs\nodejs\devspace.ps1:15 char:5
+   & "sh$exe"  "$basedir/node_modules/devspace/bin/devspace" $args
+     ~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (sh.exe:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

**Local Environment:**  
- Operating System: Win10 Pro, PScore ver 6.2.3
- node: v10.18.1 managed with nvm which is installed with scoop hence the weird paths in my error
- npm: 6.13.4

**Anything else we need to know?**  
I attempted to hardcode the directory into the `devspace.ps1` Powershell file in case the symlinks of scoop were messing with it somehow, but that didn't work either.  To do that I just changed the 2nd line of it:
```
$basedir=Split-Path "C:\Users\afmsa\scoop\persist\nvm\nodejs\v10.18.1" -Parent
```

/kind bug

**Comment by LukasGentele** [comment] 2020-02-10 13:01
@afmsavage Thanks for reporting this! It seems that npm is creating a .ps1 wrapper file which is broken. I will add a fix for this. In the meantime, just delete the file `C:\Users\afmsa\scoop\apps\nvm\current\nodejs\nodejs\devspace.ps1`. There should be another file just called `C:\Users\afmsa\scoop\apps\nvm\current\nodejs\nodejs\devspace.exe` which is the actual DevSpace binary. If you delete the ps1 file, powershell will use the exe which is correct.

**Comment by LukasGentele** [comment] 2020-02-10 13:42
Will be fixed with the next release of DevSpace. Thanks for reporting this!

**Comment by afmsavage** [comment] 2020-02-11 01:38
No worries.  I saw the devspace.exe.  I knew it was there yet it didn't click in my head to use it.  Thanks for the quick response and fix.

**Comment by SamuelColacchia** [comment] 2020-04-20 23:42
@LukasGentele I think this issue is still present in devspace@4.12.1

**Environment**
* Window 10
* PowerShell 7.0.0
* node v13.7.0
* npm 6.13.6
* nvm 1.1.7
* devspace@4.12.1

**Steps to reproduce**

`npm install -g devspace`
`git clone https://github.com/devspace-cloud/quickstart-nodejs`
`cd quickstart-nodejs`
`devspace init`

**Error**
```
Line |
  15 |    & "sh$exe"  "$basedir/node_modules/devspace/bin/devspace" $args
     |      ~~~~~~~~
     | The term 'sh.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
     | path is correct and try again.
```

If i remove C:\Users\_Insert Username here_\AppData\Roaming\nvm\v13.7.0\devspace.ps1 I get the following error
```
'"sh"' is not recognized as an internal or external command,
operable program or batch file.
```
Is there some dependency I am missing? 

As a side not if i directly download the binary add it to PATH it works.

**Comment by LukasGentele** [comment] 2020-04-20 23:54
@SamuelColacchia Thanks for reporting this. Are you able to install devspace if you are using cmd or git-bash instead of powershell?

**Comment by SamuelColacchia** [comment] 2020-04-21 21:49
@LukasGentele I just tried using cmd to install it so running
`npm ls -g --depth=0` to ensure it was not installed
`npm -g install devspace`

I got the following error:
``` bash
'"sh"' is not recognized as an internal or external command,
operable program or batch file.
```

As a side thought when I was doing this, my main computer is running windows 10 insiders so i tried in on a standard installation of windows 10 and got the same issues for powershell and cmd

Using git-bash MINGW64 it worked
``` bash
$ devspace --version
devspace version 4.12.1
```

**Comment by LukasGentele** [comment] 2020-04-22 12:13
Thanks @SamuelColacchia. I fixed the npm installer for powershell and cmd. The fix is part of the newest release v4.12.2. Would be great if you could verify that this works for you now.

**Comment by SamuelColacchia** [comment] 2020-04-23 00:52
@LukasGentele I just tried installing devspace v4.12.2 with mixed success.

First it looks like the fix for 'sh' worked!

Though I am now getting the following error when i run devspace, I think it is caused by the space in "Program Files". I tested this on a few other windows systems to see if this was the issue. Running devspace v4.12.2 worked as intended as long as there was not a space in the path to the global node_modules folder.
```
Finishing installation of DevSpace CLI
Running: node C:\Program Files\nodejs\node_modules\devspace\index.js finish-install
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by LukasGentele** [comment] 2020-04-23 01:13
@SamuelColacchia Thanks for checking again. That's great to hear that it works except for global npm paths with spaces. I will look into this and push another fix.

**Closed** 2020-04-23 01:33 UTC
