### ISSUE TITLE
devspace upgrade timeout 

### ISSUE THREAD

**Issue by kienct89** [devspace-cloud/devspace#801] opened 2019-11-12 12:24 UTC
**What happened?**  

devspace upgrade failed due to timeout
current version: 4.2.0
target version: 4.2.1

` Couldn't upgrade: read tcp : wsarecv: An existing connection was forcibly closed by the remote host.`

**What did you expect to happen instead?**  

devspace upgrade should work

**How can we reproduce the bug?** (as minimally and precisely as possible)  

execute `devspace upgrade`

**Local Environment:**  
- Operating System: windows
- Deployment method: helm

/kind bug

**Comment by FabianKramm** [comment] 2019-11-15 09:49
@kienct89 thanks for reporting, unfortunately we cannot reproduce this issue on our windows machines, but seems like this issue usually occurs if the connection to github is somehow unstable (or slow?) and github closes the connection. Since we are using a library for the upgrade process we will investigate this further and open an issue in their repository if this problem persists.

**Comment by LukasGentele** [comment] 2020-01-13 03:41
@kienct89 Is this still a problem or were you able to upgrade with the last couple of versions?

**Comment by LukasGentele** [comment] 2020-04-14 12:24
Closing this for now

**Closed by LukasGentele** 2020-04-14 12:24 UTC
