### ISSUE TITLE
`devspace sync` fails to sync - connection lost to pod

### ISSUE THREAD

**Issue by gbates101** [devspace-cloud/devspace#1027] opened 2020-03-21 00:01 UTC
**What happened?**  
When running `devspace sync --config=./devspace.yaml`, devspace locates a matching pod and attempts to sync, but repeatedly fails:
```
(base) gbates@Work /c/Projects/Tartan/docs (devspace) $ devspace sync --config=./devspace.yaml
[info]   Using kube context 'io'
[info]   Using namespace 'gbates'
[info]   Start syncing
[done] √ Sync started on /c/Projects/Tartan/docs/docs <-> /tmp/docs (Pod: gbates/docs-d6dff5667-hgtvg)
[error]  Sync Error on /c/Projects/Tartan/docs/docs: Sync - connection lost to pod gbates/docs-d6dff5667-hgtvg:  command terminated with exit code 139
[info]   Sync stopped
[info]   Restarting sync...
```

**What did you expect to happen instead?**  
Sync should be working appropriately.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Deploy any sync-enabled pod, and run `devspace sync --config=./devspace.yaml` with a `devspace.yaml` file similar to this:
```
dev:
  sync:
  - imageName: gcr.io/build/docs
    labelSelector:
      release: docs
    containerName: "docs"
    localSubPath: ./docs
    containerPath: /tmp/docs
    disableDownload: true
```

**More Details:**
I'm able to reproduce this with other projects as well, each running as a separate image/pod/deployment/chart. As long as the local folder exists and DevSync can find an existing pod, this issue can be reproduced. Downgrading from 4.7.0 to 4.6.2 fixes the issue.

**Local Environment:**  
- DevSpace Version: 4.7.0
- Operating System: Windows (WSL)
- Deployment method: helm 3

**Kubernetes Cluster:**  
- Cloud Provider: Google
- Kubernetes Version: 
    - Client Version: v1.15.5
    - Server Version: v1.14.10-gke.17

/kind bug

**Comment by gbates101** [comment] 2020-03-23 18:52
Just upgraded to 4.8.0 and I can't reproduce this. If you can't reproduce the issue in 4.8.0, feel free to close.

**Comment by FabianKramm** [comment] 2020-03-24 08:47
@gbates101 thanks for opening this issue! This error code 139 is very weird, people had this problem before (#897) and it is somehow related to the devspace version, however we didn't change anything between 4.6.2 and 4.7.0 regarding the sync, so this is very strange, because I also couldn't reproduce this on my local computer with GKE and local docker kubernetes. But good to know that it works now again with 4.8.0, so I'll close this issue for now!

**Closed by FabianKramm** 2020-03-24 08:47 UTC

**Comment by unique-vv** [comment] 2020-03-27 15:14
My Mac has this problem

`devspace version 4.8.0`

`info    Start syncing                                                                                                                                        2020-03-27T21:38:00+08:00  
 error   Sync Error on /Users/zhouwei/Documents/try/user: Sync - connection lost to pod myapp/user-6587dc5bcb-h95tc:  command terminated with exit code 139   2020-03-27T21:38:00+08:00  
 info    Sync stopped                                                                                                                                         2020-03-27T21:38:00+08:00`
